spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/student
    password:
    username:
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    generate-ddl: true
    show-sql: true
